# version: '3.7'
services:

  db:
    image: postgres:latest
    container_name: b-correspondent-db
    restart: 'always'
    ports:
      - 5432:5432
    environment:
      - DB_USER=${DBUSER}
      - DB_PASSWORD=${DBPASS}
      - DB_DATABASE=${DATABASE}
      - POSTGRES_PASSWORD=${DBPOSTGRESPASS}
      - POSTGRES_USER=postgres
    volumes:
      - ${PWD}/deploy/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
      - pg_db:/var/lib/postgresql/data
    networks:
      b-correspondent:
         ipv4_address: 192.168.22.4

  back:
    image: europe-west3-docker.pkg.dev/b-correspondent/back/back:${BACK_TAG}
    container_name: b-correspondent-back
    links:
      - db
      - storage
    depends_on:
      - db
      - storage
      - migration
      - proxy-server
    ports:
      - 12000:12000
    volumes:
      - ${HOME}/env.yaml:/server/env.yaml
      - ${HOME}/bcorrespondent_env:/server/bcorrespondent_env
      - ${HOME}/config.yaml:/server/deploy/config.yaml
      - ${PWD}/deploy/init.sh:/server/deploy/init.sh
      - ${HOME}/jwk.txt:/server/deploy/jwk.txt
      - ${HOME}/front_env:/server/front_env
    networks:
      b-correspondent:
         ipv4_address: 192.168.22.6

  front:
    image: europe-west3-docker.pkg.dev/b-correspondent/front/front:${FRONT_TAG}
    container_name: b-correspondent-front
    restart: 'always'
    ports:
      - 3001:3000
    networks:
      b-correspondent:
        ipv4_address: 192.168.22.7

  storage:
    image: minio/minio:latest
    container_name: b-correspondent-file-storage
    restart: 'always'
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASS}
    command: server --address ":9000" --console-address ":9001" /data
    networks:
      b-correspondent:
         ipv4_address: 192.168.22.5

  migration:
    image: liquibase/liquibase:latest
    container_name: b-correspondent-migration
    depends_on:
      - db
      - storage
    volumes:
      - ${PWD}/migration/:/liquibase/changelog
      - ${PWD}/migration/liquibase_policy_init.sh:/liquibase/liquibase_policy_init.sh
      - ${PWD}/bcorrespondent_env:/liquibase/b_correspondent_env
    command: ['./liquibase_policy_init.sh']
    networks:
      - b-correspondent

  proxy-server:
    image: nginx
    container_name: b-correspondent-proxy-server
    volumes:
      - ${PWD}/deploy/nginx/proxy.conf:/etc/nginx/nginx.conf
      - ${HOME}/.htpasswd:/etc/apache2/.htpasswd
      - ${PWD}/deploy/nginx/ssl/front/b-correspondent.crt:/etc/nginx/certs/front/b-correspondent.crt
      - ${PWD}/deploy/nginx/ssl/front/b-correspondent.key:/etc/nginx/certs/front/b-correspondent.key
      - ${PWD}/deploy/nginx/ssl/back/b-correspondent.crt:/etc/nginx/certs/back/b-correspondent.crt
      - ${PWD}/deploy/nginx/ssl/back/b-correspondent.key:/etc/nginx/certs/back/b-correspondent.key
      - ${PWD}/deploy/nginx/ssl/global.pass:/etc/keys/global.pass
    ports:
      - 443:443
      - 80:80
    networks:
      - b-correspondent

  pgadmin:
    image: dpage/pgadmin4
    container_name: b-correspondent_pgadmin4
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMINEMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMINPASS}
      SCRIPT_NAME: /pgadmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      b-correspondent:
         ipv4_address: 192.168.22.8

volumes:
  pg_db: {}
  minio_data: {}
  pgadmin-data: {}

networks:
  b-correspondent:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.22.0/25
# vim: et:sw=2