# version: '3.7'
services:

  db:
    image: postgres
    container_name: b-correspondent_db
    restart: 'always'
    ports:
      - 5432:5432
    environment:
      - DB_USER=${DBUSER}
      - DB_PASSWORD=${DBPASS}
      - DB_DATABASE=${DATABASE}
      - POSTGRES_PASSWORD=${DBPOSTGRESPASS}
      - POSTGRES_USER=postgres
    volumes:
      - ${PWD}/deploy/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d/
      - pg_db:/var/lib/postgresql/data
    networks:
      b-correspondent:
         ipv4_address: 192.168.22.4

  back:
    image: europe-west3-docker.pkg.dev/b-correspondent/back/back:${BACK_TAG}
    container_name: b-correspondent_back
    links:
      - db
      - storage
    depends_on:
      - db
      - storage
      - migration
      - proxy-server
    ports:
      - 12000:12000
    volumes:
      - ${HOME}/env.yaml:/server/env.yaml
      - ${HOME}/bcorrespondent_env:/server/bcorrespondent_env
      - ${HOME}/config.yaml:/server/deploy/config.yaml
      - ${PWD}/deploy/init.sh:/server/deploy/init.sh
      - ${HOME}/jwk.txt:/server/deploy/jwk.txt
      - ${HOME}/front_env:/server/front_env
      - ${PWD}/country-code.csv:/server/country-code.csv
      - ${PWD}/template:/server/template
    networks:
      b-correspondent:
         ipv4_address: 192.168.22.6

  front:
    image: europe-west3-docker.pkg.dev/b-correspondent/front/front:${FRONT_TAG}
    container_name: b-correspondent_front
    restart: 'always'
    ports:
      - 3001:3000
    networks:
      b-correspondent:
        ipv4_address: 192.168.22.7

  storage:
    image: minio/minio
    container_name: b-correspondent-file-storage
    restart: 'always'
    ports:
      - 9001:9001
      - 9000:9000
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASS}
    command: server --address ":9000" --console-address ":9001" /data
    networks:
      b-correspondent:
         ipv4_address: 192.168.22.5

  migration:
    image: liquibase/liquibase
    container_name: b-correspondent_migration
    depends_on:
      - db
      - storage
    environment:
      - DB_USER=${DBUSER}
      - DB_PASSWORD=${DBPASS}
      - DB_DATABASE=${DATABASE}
    volumes:
      - ${PWD}/migration/:/liquibase/changelog
      - ${PWD}/migration/liquibase_policy_init.sh:/liquibase/liquibase_policy_init.sh
    command: ['./liquibase_policy_init.sh']
    networks:
      - b-correspondent

  proxy-server:
    image: nginx
    container_name: b-correspondent-proxy-server
    volumes:
      - ${PWD}/deploy/nginx/proxy.conf:/etc/nginx/nginx.conf
      - ${HOME}/.htpasswd:/etc/apache2/.htpasswd
      - ${PWD}/deploy/nginx/ssl/front/b-correspondent.crt:/etc/nginx/certs/front/b-correspondent.crt
      - ${PWD}/deploy/nginx/ssl/front/b-correspondent.key:/etc/nginx/certs/front/b-correspondent.key
      - ${PWD}/deploy/nginx/ssl/back/b-correspondent.crt:/etc/nginx/certs/back/b-correspondent.crt
      - ${PWD}/deploy/nginx/ssl/back/b-correspondent.key:/etc/nginx/certs/back/b-correspondent.key
      - ${PWD}/deploy/nginx/ssl/global.pass:/etc/keys/global.pass
    ports:
      - 443:443
      - 80:80
    networks:
      - b-correspondent

  pgadmin:
    image: dpage/pgadmin4
    container_name: b-correspondent_pgadmin4
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMINEMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMINPASS}
      SCRIPT_NAME: /pgadmin
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    networks:
      b-correspondent:
         ipv4_address: 192.168.22.8

  # The 'setup' service runs a one-off script which initializes users inside
  # Elasticsearch — such as 'logstash_internal' and 'kibana_system' — with the
  # values of the passwords defined in the '.env' file. It also creates the
  # roles required by some of these users.
  #
  # This task only needs to be performed once, during the *initial* startup of
  # the stack. Any subsequent run will reset the passwords of existing users to
  # the values defined inside the '.env' file, and the built-in roles to their
  # default permissions.
  #
  # By default, it is excluded from the services started by 'docker compose up'
  # due to the non-default profile it belongs to. To run it, either provide the
  # '--profile=setup' CLI flag to Compose commands, or "up" the service by name
  # such as 'docker compose up setup'.
  # setup:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
  #   init: true
  #   volumes:
  #     - ${PWD}/deploy/elk/setup/entrypoint.sh:/entrypoint.sh:ro,Z
  #     # - ${PWD}/deploy/elk/setup/lib.sh:/lib.sh:ro,Z
  #   environment:
  #     ELASTIC_PASSWORD: ${ELASTICPASS}
  #     LOGSTASH_INTERNAL_PASSWORD: ${LOGSTASH_INTERNAL_PASSWORD}
  #     KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD}
  #   networks:
  #     - b-correspondent
  #   depends_on:
  #     - elasticsearch

  kibana:
    image: kibana:8.10.4
    ports:
      - 5601:5601
    volumes:
      - ${HOME}/kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      KIBANA_SYSTEM_PASSWORD: ${KIBANA_SYSTEM_PASSWORD}
    networks:
      b-correspondent:
         ipv4_address: 192.168.22.11
    depends_on:
      - setup

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    volumes:
      - ${HOME}/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro,Z
      - elasticsearch:/usr/share/elasticsearch/data:Z
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      ELASTIC_PASSWORD: ${ELASTICPASS}
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      # Bootstrap password.
      # Used to initialize the keystore during the initial startup of
      # Elasticsearch. Ignored on subsequent runs.
      # Use single node discovery in order to disable production mode and avoid bootstrap checks.
      # see: https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html
      discovery.type: single-node
    networks:
      b-correspondent:
        ipv4_address: 192.168.22.12
    restart: unless-stopped

volumes:
  pg_db: {}
  minio_data: {}
  pgadmin-data: {}
  elasticsearch: {}

networks:
  b-correspondent:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.22.0/25
# vim: et:sw=2